### ISSUE TITLE
fparser2 failed to parse an import statement within function subprogram

### ISSUE THREAD

**Issue by grnydawn** [stfc/fparser#144] opened 2018-12-18 16:21 UTC
interface
    function name(...)
        import     <== failed with FortranSyntaxError exception
        integer, intent(in) :: pcols
        ...
    end function
end interface

**Comment by rupertford** [comment] 2019-01-03 14:41
@grnydawn, could you please give the actual code as the following example works for me ...

```
xed67771@arcgdel01:~/proj/fparser/src/fparser$ cat tmp.f90
program test
  use, intrinsic :: ISO_C_BINDING
  interface
     function cels_from_fahr(degrees_fahr) result(degrees_cels)
       IMPORT :: C_INT
       integer(C_INT), intent(in) :: degrees_fahr
       integer(C_INT)             :: degrees_cels
     end function cels_from_fahr
  end interface
end program test
xed67771@arcgdel01:~/proj/fparser/src/fparser$ gfortran -c tmp.f90
xed67771@arcgdel01:~/proj/fparser/src/fparser$ scripts/fparser2.py tmp.f90
PROGRAM test
  USE, INTRINSIC :: ISO_C_BINDING
  INTERFACE
    FUNCTION cels_from_fahr(degrees_fahr) RESULT(degrees_cels)
      IMPORT :: C_INT
      INTEGER(KIND = C_INT), INTENT(IN) :: degrees_fahr
      INTEGER(KIND = C_INT) :: degrees_cels
    END FUNCTION cels_from_fahr
  END INTERFACE
END PROGRAM test
xed67771@arcgdel01:~/proj/fparser/src/fparser$ 
```

**Comment by rupertford** [comment] 2019-01-08 14:55
Having been taught to read properly by @arporter I can reproduce the reported bug ...

```
xed67771@arcgdel01:~/proj/fparser/src/fparser$ cat tmp.f90
program test
  use, intrinsic :: ISO_C_BINDING
  interface
     function cels_from_fahr(degrees_fahr) result(degrees_cels)
       IMPORT
       integer(C_INT), intent(in) :: degrees_fahr
       integer(C_INT)             :: degrees_cels
     end function cels_from_fahr
  end interface
end program test
xed67771@arcgdel01:~/proj/fparser/src/fparser$ scripts/fparser2.py tmp.f90
Syntax error: at line 5
>>>       IMPORT

parsing 'tmp.f90' failed at line #5'IMPORT'
started at line #1'program test'
```

**Comment by rupertford** [comment] 2019-01-10 09:17
Created branch import_fix

**Comment by arporter** [comment] 2020-01-03 11:58
#206 has been merged. Closing this issue.

**Closed by arporter** 2020-01-03 11:58 UTC
Labels: in progress
