### ISSUE TITLE
Fixes for parsing LFRic kernels with fparser2

### ISSUE THREAD

**Issue by TeranIvy** [stfc/fparser#69] opened 2018-01-12 17:26 UTC
I started testing fparser2 on LFRic kernels and identified some bugs which caused it to fail, which are now fixed. I successfully parsed two kernels so far and will attempt to parse the rest of them as well.

**Comment by rupertford** [comment] 2018-01-12 19:22
That's great Iva. Out of interest, are you currently a) getting fparser2 to successfully complete, b) the previous plus successfully compiling, c) the previous plus successfully running the resultant kernels or d) the previous plus getting the same results as the original kernels?

**Comment by TeranIvy** [comment] 2018-01-16 13:25
Hi @rupertford! So far only b) with gfortran and that with manually breaking up the resultant joined lines of code. The trouble is that fparser2 removes continuations from the original code and kernels can have many metadata arguments. I think fparser2 should keep continued lines and the comments from the original code (it does not do either currently).

**Comment by TeranIvy** [comment] 2018-01-16 20:21
All LFRic kernels are now parsed without fparser2 falling over. The next step is to figure out how to make fparser2 keeping line continuation and not creating one long line. A bit of help from @rupertford and/or @arporter would be much appreciated here :)

There were two fixes required: `class Private_Components_Stmt` and `class Loop_Control`. The latter did not behave correctly when creating string: it was always adding "," (optional argument) instead of only when it was detected. This is now fixed but it raises the need to modify tests for labeled `DO` constructs to include cases with and without "," as both are valid Fortran (e.g. `DO 20, i = 1, 5` or `DO 20 i = 1, 5`).

Regarding the tests, it would be good to add some real Fortran files instead of writing code in Python files. @rupertford, @arporter, can I move/expand the tests for various `DO` constructs to Fortran files (perhaps located in a subdirectory like `test_files` in PSyclone)?

**Comment by rupertford** [comment] 2018-01-17 00:15
Hi Iva.

It's great that you have managed to parse all LFRic kernels. That brings us closer to migrating from fparser to fparser2.

I wonder if the long line issue is something we can live with for the time being? fparser does the same thing (removes continuations) and we've managed to work with it in LFRic so far.

I'm not sure why you necessarily want to load a file, rather than adding the code as a Python string. The main reason I can think of would be if the code was quite large and/or is used in different files but I presume you only require something simple like the following for a test

{{{
subroutine x()
  do 20 i = 1, 5
  ...
end subroutine
}}}

which I would argue is better to keep as a string rather than a separate file. Could you explain why you think a file would be better?

**Comment by hiker** [comment] 2018-01-17 00:52
*grin* Considering https://github.com/stfc/PSyclone/pull/122: to avoid pylint's duplicated code warnings :) (sorry, couldn't resist)

**Comment by rupertford** [comment] 2018-01-17 01:00
I'll let you off :-).

To avoid duplicated code warnings you don't need to store things in a file though, you could modify the string rather than replicate it, if changes are small. In Iva's example we simply replace '20' with '20,' to get the second test case. Or is that not the issue?

**Comment by hiker** [comment] 2018-01-17 01:20
Yes, but considering:
```
   test_code = getLoopTestCode()
   test_code.replace('20,', '20 ')
```
that is hard to understand (another function to find first) and fragile (a change to spaces in getLoopTestCode will potentially break this test code.
But let's stop my comments here for now, I am just slowly working on eroding your resistance to the pylintrc file ;)

**Comment by arporter** [comment] 2018-01-17 17:41
I'm with Rupert on this one. Just declaring a string and then manipulating it as required is pretty simple. If someone goes in and changes that string then they have to accept the consequences :-)
While I'm here, @TeranIvy has mentioned comments so I just thought I'd flag up #68 where I'm fighting with the internals of fparser2 so that it doesn't throw them away. As a first step, we will still throw-away in-line comments (because they're hard and because they can't be directives).

**Comment by TeranIvy** [comment] 2018-01-17 21:31
Ok, I managed to go through long lines by removing "-l" option in LFRic makefile for Psyclone when building the code. As far as I can see PSyclone wraps lines to 132 characters if required so can modify long lines returned by fparser2 just as it does currently with fparser. Regarding that, I agree that fparser2 not preserving continuation is not an issue if it is used from PSyclone. It might be if it is used on its own. 
Regarding comments in code:@arporter, thank you very much for pointing me to #68. I will happily update my branch when this is merged to master :)

The LFRic build, however, still fails because there is another bug which produces invalid Fortran in parsed kernels. I did not notice it before because I compiled the kernels which happened to be parsed correctly. The fparser2 tests of course work because they assert the wrong thing. 
Using real Fortran examples for testing fparser2 would be much more efficient since it could flag invalid Fortran when they are compiled. It would be helpful for fparser2 developers and also serve as quality assurance for  the users. This approach would have exposed the fparser2 bugs much sooner and with much less effort than going back and forth between (incorrect) parsing and trying to build complex scientific codes.

**Comment by rupertford** [comment] 2018-01-18 11:18
FYI, PSyclone includes a separate postprocessing option (separate to the parsers) which implements line wrapping. There is a default length which can be changed. It's not a full parser so there are pathological cases where it will go wrong but it seems to work OK.

I agree that it would be nice to preserve line continuations and even to be able to specify a maximum output line length within the parsers.

As for bugs, I still don't understand the argument for including real examples for unit tests. That's not to say the argument is wrong of course. I certainly agree that it is useful to try to get fparser to run on as many codes as possible, particularly ones we care about, but if a bug is found then I think we should reproduce this in a unit test (or set of unit tests) that is/are as small as possible.

**Comment by TeranIvy** [comment] 2018-01-18 17:32
Hi @rupertford! Yep, I removed line wrapping from compile options and am happy to report that LFRic trunk builds and runs fine with parsed kernels for Intel and GNU compilers (Rose suite tests are all green, which means the code returns same numerical values). Cray has line length limit of 255 characters and I couldn't figure out how to extend the line limit for Portland, so these fail.

OK, I will add as many small tests which are valid Fortran as I can (I test the statements by compiling small programs first to see what is valid and what is not). I will also include logging for invalid Fortran.

**Comment by arporter** [comment] 2018-01-19 15:18
re. the production of invalid Fortran - one option would be to copy (some of) the machinery from the PSyclone test suite that allows generated code to be put through a real Fortran compiler. That's definitely something for another Issue though.

**Comment by TeranIvy** [comment] 2018-01-19 15:49
Thanks, @arporter. For now I put logging messages for these cases. A question about tests: sometimes "assert" is used and sometimes "assert_equal". Which one is preferred?

**Comment by arporter** [comment] 2018-01-22 09:18
Please use `assert` - `assert_equal` comes from `nose` which we are trying to get rid of. I don't quite understand what you mean about logging? Do you mean to flag cases where adding a compilation test would be good?

**Comment by TeranIvy** [comment] 2018-01-22 10:54
Ok, I'll use `assert`.  By logging I mean raising error messages for attempts to produce invalid Fortran.

**Comment by arporter** [comment] 2018-02-26 11:14
PR #72 is now on master and changelog has been updated. Closing issue.

**Closed by arporter** 2018-02-26 11:14 UTC
Labels: bug, in progress
