### ISSUE TITLE
Having format statement at the same source line with write statement

### ISSUE THREAD

**Issue by grnydawn** [stfc/fparser#161] opened 2019-01-10 17:29 UTC
Parsing following line caused FortranSyntaxError exception.

write(char_temp,1100) 'tavg',ns ;  1100 format (a,i1)

I am not sure if standard supports the syntax, though.

**Comment by rupertford** [comment] 2020-01-03 01:59
This seems to be valid Fortran 2003. At least gfortran -std=f2003 ... is happy.
I can reproduce the error in fparser.
If we take the following code ...
```
>>> code = '''
program test
write(char_temp,1100) 'tavg',ns ; 1100 format (a,i1)
1100 format (a,i1)
end program test
```
and run it through the string reader ...
```
>>> reader = FortranStringReader(code)
>>> reader.next()
Line('program test',(2, 2),None,None,<reader>)
>>> reader.next()
Line(u"write(char_temp,1100) 'tavg',ns",(3, 3),None,None,<reader>)
>>> reader.next()
Line(u'1100 format (a,i1)',(3, 3),None,None,<reader>)
>>> reader.next()
Line('format (a,i1)',(4, 4),1100,None,<reader>)
>>> 
```
it can be seen that the format line is captured differently depending on whether it is at the beginning of the line or after a `;`. This could be the cause of the problem.

**Comment by arporter** [comment] 2020-01-07 10:12
#233 has been merged. Closing issue.

**Closed by arporter** 2020-01-07 10:12 UTC
Labels: in progress
