### ISSUE TITLE
Bug parsing write statement

### ISSUE THREAD

**Issue by bonfus** [stfc/fparser#64] opened 2017-12-14 15:30 UTC
The following code compiles fine but is not parsed by the Fortran2003 module.

    program ma
          WRITE(*,'(5X,"q_mesh =",4F12.8)') 1.d0, 2.d0, 3.d0, 4.d0
    end program ma

code used:

    # coding: utf-8
    from fparser.api import Fortran2003
    from fparser.readfortran import FortranFileReader
    reader = FortranFileReader("test.f90")
    Fortran2003.Program(reader)

**Comment by arporter** [comment] 2017-12-18 10:06
Thanks for this report. I can reproduce the failure and will investigate further.

**Comment by arporter** [comment] 2017-12-18 15:15
Bug was due to an over-zealous search for the '=' character in keyword-value pairs. It failed to allow for the case where an '=' character is in fact inside a string.

**Comment by rupertford** [comment] 2018-01-12 00:59
pr #66 is now on master so closing this issue.

**Closed by rupertford** 2018-01-12 00:59 UTC
Labels: bug
