### ISSUE TITLE
Allow the reader cache to be disabled

### ISSUE THREAD

**Issue by ScottWales** [stfc/fparser#74] opened 2018-02-23 00:43 UTC
I am looking at adding Python 3 support to PSyclone. It is generating modules by parsing some sample text, then modifying the resulting parse tree, e.g.
```python
code = """\
module vanilla
end module vanilla
"""
tree = fparser.api.parse(code)
# modify the resulting tree
```
When running under Python 3 the `code` string is always the same object (due to improved string optimisation I guess). The `FortranParser.__init__()` function notices this, so reads the tree from its cache.

When PSyclone modifies the tree, these modifications are altering the cached parse tree as well. If a second module gets created the new module also gets read from the cache (since the code string is identical), but the tree returned by `api.parse()` does not match the given code.

An easy way to fix this would be to add a flag to `api.parse()` that disables the cache. 

A test for this behaviour:
```python
def test_fparser_cache():
    """
    Modifications to a tree should not affect future parsing
    """
    # Create a module and add some statements to it
    module = """\
module vanilla
end module vanilla
"""
    tree0 = fparser.api.parse(module)

    code = """\
implicit none
"""
    reader = fparser.readfortran.FortranStringReader(code)
    statement = fparser.typedecl_statements.Implicit(tree0, reader.next())
    tree0.content[0].content.insert(0, statement)

    # Create a new module from the original code
    tree1 = fparser.api.parse(module)

    # We should not get back the tree that has been modified
    assert str(tree1) != str(tree0)
```

**Comment by arporter** [comment] 2018-02-26 10:04
Since it is PSyclone's use of the fparser tree that is the problem, maybe the responsibility lies with PSyclone to take a deep copy of the tree before it modifies it? I've just taken a look at PSyclone's `f2pygen.py` and see that the code in question is effectively in the constructor for e.g. `ModuleGen`. Therefore I think it should be PSyclone's responsibility to ensure it is returning a new object from that constructor. I'm not sure whether it is cleaner to do a deep copy of the tree returned by fparser or to add a disable-cache flag to the parse method of fparser. The former is probably a smaller change.

**Comment by ScottWales** [comment] 2018-02-26 11:17
It looks like `copy.deepcopy` does not like fparser's parse trees, failing with a recursion error. Do you know of a way to get around this?

```
    def test_fparser_deepcopy():
        module = """\
    module vanilla
    end module vanilla
    """
        tree = fparser.api.parse(module)
>       copy.deepcopy(tree)

test_parser.py:15: 
_ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ _ 
../miniconda3/envs/psyclone/lib/python3.6/copy.py:180: in deepcopy
    y = _reconstruct(x, memo, *rv)
# ...
../miniconda3/envs/psyclone/lib/python3.6/site-packages/fparser/base_classes.py:103: in __getattr__
    if name not in self._attributes:
E   RecursionError: maximum recursion depth exceeded
!!! Recursion detected (same locals & position)
```

**Comment by arporter** [comment] 2018-02-26 11:24
Oh! That's not good. I don't know of a work-around sadly. Maybe we'd better revert to plan A (alter fparser's `parse` routine)...

**Comment by hiker** [comment] 2018-02-26 12:13
I actually have been wondering about this parsing and modifying code while debugging the profiler code - it seems to be a lot of overhead to first create a dummy string, create a reader, convert it to a Line, then parse the line - and then replace some or most of the fields with the values actually needed.
 Example (TypeDeclGen):
```
        reader = FortranStringReader("type(vanillatype) :: vanilla")
        reader.set_mode(True, False)  # free form, strict
        myline = reader.next()

        from fparser.typedecl_statements import Type
        self._typedecl = Type(parent.root, myline)
        self._typedecl.selector = ('', datatype)
        self._typedecl.attrspec = my_attrspec
        self._typedecl.entity_decls = local_entity_decls
```
I mean this code even assumes a fixed data structure from fparser (selector being a tuple).
What about instead:
```
self._typedecl = Type(parent.root, reader=None, type="vanillatype", var="vanilla", selector=[], attrspec=["save"])
```
And we can probably come up with a cleaner API than setting reader=None.

This makes PSyclone a lot cleaner, faster and shorter (though of course fparser will get somewhat bigger), and might just avoid the whole problem of copying and modifying the AST in the first place (though of course fixing this might not be a bad idea either).

**Comment by rupertford** [comment] 2018-02-26 12:24
It sounds like the problem is that the `code` string is static. If we create a new code string each time with its own memory space then I guess it would be OK - although doing that might not be that easy in Python3!

**Comment by rupertford** [comment] 2018-02-26 13:01
In answer to @hiker. This code is actually part of f2pygen (or fgenerator if we ever split it out into its own repo). fparser just parses code and is not designed to generate code. To get round this in f2pygen I create a skeleton/vanilla fortran string, parse it with fparser, then modify it. As you say, this is clunky. However, I could not find a way round this due to the way fparser was written and due to my limited understanding of fparser. If your suggestion gets round this then great! The particular example in question is slightly different to your example, in that it needs to create a new fparser tree rather than add an element to it.

**Comment by arporter** [comment] 2018-02-28 11:56
I've had a look in PSyclone and see that in `psyclone.parse()` we always wipe the fparser cache before we do anything:

        # drop cache
        fparser.parsefortran.FortranParser.cache.clear()

Given the complexities around trying to ensure Python gives us a new string object, I think the best bet would be to alter the interface to fparser's `api.parse()` by adding e.g. `clear_cache=True` as an argument. I'm aware this would change the default behaviour of the parser but since caching is only a performance issue, I think we can live with that. This would then help to minimise the changes required to PSyclone to support Python3.

**Comment by arporter** [comment] 2018-03-26 12:28
I've taken the liberty of tidying the `test_api.py` file for pylint/pep8 while I was there.

**Comment by TeranIvy** [comment] 2018-04-20 09:26
PR #78 is now on master and changelog has been updated. Closing issue.

**Closed** 2018-04-20 09:26 UTC
Labels: in progress
